/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cmms.models;

import com.google.common.base.Strings;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 *
 * @author gpatitakis
 */
@Entity
@Table(name = "cause_type")
public class CauseType implements Serializable {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotNull
    private String name;

    @NotNull
    @Column(name = "view_name")
    private String viewName;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------
    public CauseType() {
    }

    public CauseType(Long id) {
        this.id = id;
    }

    // Getter and setter methods
    public Long getId() {
        return id;
    }

    public void setId(Long value) {
        this.id = value;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getViewName() {
        return viewName;
    }

    public void setViewName(String viewName) {
        this.viewName = viewName;
    }

    public void setChanges(CauseType value) {
        if (!Strings.isNullOrEmpty(value.name) && value.name.equals(this.name)) {
            this.name = value.name;
        }
        if (!Strings.isNullOrEmpty(value.viewName) && value.viewName.equals(this.viewName)) {
            this.viewName = value.viewName;
        }
    }

    @Override
    public String toString() {
        return "CouseType{"
                + "id=" + id
                + ", name=" + name
                + ", viewName=" + viewName + '}';
    }
} // class CauseType
