package cmms.models;

import com.google.common.base.Strings;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 *
 * @author gpatitakis
 */
@Entity
@Table(name = "cause")
public class Cause implements Serializable {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotNull
    private Long type;

    @NotNull
    private Long department;

    @NotNull
    @Column(columnDefinition = "b'1'")
    private Boolean enable;

    private String code;

    private String description;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------
    public Cause() {
    }

    public Cause(Long id) {
        this.id = id;
    }

    public Cause(Long type, Long department, Boolean enable, String code, String description) {
        this.type = type;
        this.department = department;
        this.enable = enable;
        this.code = code;
        this.description = description;
    }

    // Getter and setter methods
    public Long getId() {
        return id;
    }

    public void setId(Long value) {
        this.id = value;
    }

    public long getType() {
        return type;
    }

    public void setType(long value) {
        this.type = value;
    }

    public Long getDepartment() {
        return department;
    }

    public void setDepartment(Long value) {
        this.department = value;
    }

    public Boolean isEnable() {
        return enable;
    }

    public void setEnable(Boolean value) {
        this.enable = value;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String value) {
        this.code = value;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setChanges(Cause value) {
        if (!value.type.equals(this.type)) {
            this.type = value.type;
        }
        if (value.department != null && !value.department.equals(this.department)) {
            this.department = value.department;
        }
        if (!value.enable.equals(this.enable)) {
            this.enable = value.enable;
        }
        if (!Strings.isNullOrEmpty(value.code) && value.code.equals(this.code)) {
            this.code = value.code;
        }
        if (!Strings.isNullOrEmpty(value.description) && value.description.equals(this.description)) {
            this.description = value.description;
        }
    }

    @Override
    public String toString() {
        return "Cause{"
                + "id=" + id
                + ",type=" + type
                + ",department=" + department
                + ",enable=" + enable
                + ",code=" + code
                + ",description=" + description + '}';
    }
} // class Cause
