package cmms.models;

import cmms.helpers.CustomDateDeserializer;
import cmms.helpers.CustomDateSerializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.base.Strings;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

/**
 *
 * @author gpatitakis
 */
@Entity
@Table(name = "f57790")
public class Damage implements Serializable {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "Q32UKID")
    private Long id;

    @JsonSerialize(using = CustomDateSerializer.class)
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @NotNull
    @Column(name = "Q32TRDJ")
    private Date created;

    @Column(name = "Q32USER")
    private String user;

    @NotNull
    @Column(name = "Q32LOCNKEY")
    private Long department;

    @NotNull
    private String Q32LOCN;

    @NotNull
    private String Q32$STEP;

    private String Q32MCU;

    @NotNull
    @Column(name = "Q32KEYTYPE")
    private Long type;

    @NotNull
    @Column(name = "Q32KEY")
    private Long cause;

    @Column(name = "Q32$IDFAC")
    private Long machine;

    private String Q32$FAAL1;

    private String Q32$LINE;

    private String Q32$SHFT;

    private String Q32$IDDLR;

    @NotNull
    @Column(name = "Q32UORG")
    private Long duration;

    private Long Q32UKIDP;

    private String Q32$STA;

    @NotNull
    @Column(insertable = true, updatable = true)
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    private Date Q32UPMJ;

    private String Q32UPID;

    private String Q32UPMB;

    @Column(name = "Q32NOTE")
    private String note;

    @NotNull
    @Column(name = "Q32DELETED", columnDefinition = "0")
    private Boolean deleted;

    @Transient
    private Long minuteDuration;

    @Transient
    private Long secondsDuration;

    @Transient
    private String descriptionType;

    @Transient
    private String descriptionDepartment;

    @Transient
    private String descriptionMachine;

    @Transient
    private String descriptionCause;

    @Transient
    private String descriptionUser;

    @Transient
    private String descriptionSubcause;

    private Damage(Builder builder) {
        this.machine = builder.machine;
    }

    // ------------------------
    // PUBLIC METHODS
    // ------------------------
    public Damage() {
    }

    public Damage(Long id) {
        this.id = id;
    }

    // Getter and setter methods
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getCreated() {
        return created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public Long getDepartment() {
        return department;
    }

    public void setDepartment(Long department) {
        this.department = department;
    }

    public String getQ32MCU() {
        return Q32MCU;
    }

    public void setQ32MCU(String Q32MCU) {
        this.Q32MCU = Q32MCU;
    }

    public Long getType() {
        return type;
    }

    public void setType(Long type) {
        this.type = type;
    }

    public Long getCause() {
        return cause;
    }

    public void setCause(Long cause) {
        this.cause = cause;
    }

    public String getDescriptionSubcause() {
        return descriptionSubcause;
    }

    public void setDescriptionSubcause(String descriptionSubcause) {
        this.descriptionSubcause = descriptionSubcause;
    }

    public String getQ32LOCN() {
        return Q32LOCN;
    }

    public void setQ32LOCN(String Q32LOCN) {
        this.Q32LOCN = Q32LOCN;
    }

    public Long getMachine() {
        return machine;
    }

    public void setMachine(Long machine) {
        this.machine = machine;
    }

    public String getQ32$FAAL1() {
        return Q32$FAAL1;
    }

    public void setQ32$FAAL1(String Q32$FAAL1) {
        this.Q32$FAAL1 = Q32$FAAL1;
    }

    public String getQ32$LINE() {
        return Q32$LINE;
    }

    public void setQ32$LINE(String Q32$LINE) {
        this.Q32$LINE = Q32$LINE;
    }

    public String getQ32$SHFT() {
        return Q32$SHFT;
    }

    public void setQ32$SHFT(String Q32$SHFT) {
        this.Q32$SHFT = Q32$SHFT;
    }

    public String getQ32$IDDLR() {
        return Q32$IDDLR;
    }

    public void setQ32$IDDLR(String Q32$IDDLR) {
        this.Q32$IDDLR = Q32$IDDLR;
    }

    public Long getDuration() {
        return duration;
    }

    public void setDuration(Long duration) {
        this.duration = duration;
    }

    public Long getQ32UKIDP() {
        return Q32UKIDP;
    }

    public void setQ32UKIDP(Long Q32UKIDP) {
        this.Q32UKIDP = Q32UKIDP;
    }

    public String getQ32$STA() {
        return Q32$STA;
    }

    public void setQ32$STA(String Q32$STA) {
        this.Q32$STA = Q32$STA;
    }

    public Date getQ32UPMJ() {
        return Q32UPMJ;
    }

    public void setQ32UPMJ(Date Q32UPMJ) {
        this.Q32UPMJ = Q32UPMJ;
    }

    public String getQ32UPID() {
        return Q32UPID;
    }

    public void setQ32UPID(String Q32UPID) {
        this.Q32UPID = Q32UPID;
    }

    public String getQ32UPMB() {
        return Q32UPMB;
    }

    public void setQ32UPMB(String Q32UPMB) {
        this.Q32UPMB = Q32UPMB;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public Boolean getDeleted() {
        return deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    public String getDescriptionType() {
        return descriptionType;
    }

    public void setDescriptionType(String descriptionType) {
        this.descriptionType = descriptionType;
    }

    public String getDescriptionDepartment() {
        return descriptionDepartment;
    }

    public void setDescriptionDepartment(String descriptionDepartment) {
        this.descriptionDepartment = descriptionDepartment;
    }

    public String getDescriptionMachine() {
        return descriptionMachine;
    }

    public void setDescriptionMachine(String descriptionMachine) {
        this.descriptionMachine = descriptionMachine;
    }

    public String getDescriptionCause() {
        return descriptionCause;
    }

    public void setDescriptionCause(String descriptionCause) {
        this.descriptionCause = descriptionCause;
    }

    public String getDescriptionUser() {
        return descriptionUser;
    }

    public void setDescriptionUser(String descriptionUser) {
        this.descriptionUser = descriptionUser;
    }

    public String getQ32$STEP() {
        return Q32$STEP;
    }

    public void setQ32$STEP(String Q32$STEP) {
        this.Q32$STEP = Q32$STEP;
    }

    public Long getMinuteDuration() {
        return minuteDuration;
    }

    public void setMinuteDuration(Long minuteDuration) {
        this.minuteDuration = minuteDuration;
    }

    public Long getSecondsDuration() {
        return secondsDuration;
    }

    public void setSecondsDuration(Long secondsDuration) {
        this.secondsDuration = secondsDuration;
    }

    @SuppressWarnings("null")
    public void setChanges(Damage value) {
        if (!value.type.equals(this.type)) {
            this.type = value.type;
        }
        if (value.department != null && !value.department.equals(this.department)) {
            this.department = value.department;
        }
        if (!value.machine.equals(this.machine)) {
            this.machine = value.machine;
        }
        if (!value.cause.equals(this.cause)) {
            this.cause = value.cause;
        }
        if (!value.user.equals(this.user)) {
            this.user = value.user;
        }
        if (value.created != this.created) {
            this.created = value.created;
        }
        if (!value.duration.equals(this.duration)) {
            this.duration = value.duration;
        }
        if (!Strings.isNullOrEmpty(value.note) && !value.note.equals(this.note)) {
            this.note = value.note;
        }
    }

    @Override
    public String toString() {
        return "Damage{"
                + "id=" + id
                + ",type=" + type
                + ",department=" + department
                + ",machine=" + machine
                + ",cause=" + cause
                + ",subcause=" + descriptionSubcause
                + ",created=" + created
                + ",duration=" + duration
                + ",user=" + user
                + ",note=" + note + '}';
    }

    public static class Builder {

        private Long machine;

        public Builder setMachine(Long machine) {
            this.machine = machine;

            return this;
        }

        public Damage build() {
            return new Damage(this);
        }
    }
} // class Damage
