/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cmms.models;

import com.google.common.base.Strings;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 *
 * @author gpatitakis
 */
@Entity
@Table(name = "vdelays")
public class Delay implements Serializable {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------
    // An autogenerated id (unique for each user in the db)
    @NotNull
    @Column(name = "DRKEY")
    @Id
    private Long id;

    @NotNull
    @Column(name = "DRLOCNKEY")
    private Long department;

    private Integer DRKY;

    @Column(name = "DRDL01")
    private String description;

    private String DRLOCN;

    private String DR$STEP;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------
    public Delay() {
    }

    public Delay(Long department) {
        this.department = department;
    }

    // Getter and setter methods
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getDepartment() {
        return department;
    }

    public void setDepartment(Long department) {
        this.department = department;
    }

    public Integer getDRKY() {
        return DRKY;
    }

    public void setDRKY(Integer DRKY) {
        this.DRKY = DRKY;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDRLOCN() {
        return DRLOCN;
    }

    public void setDRLOCN(String DRLOCN) {
        this.DRLOCN = DRLOCN;
    }

    public String getDR$STEP() {
        return DR$STEP;
    }

    public void setDR$STEP(String DR$STEP) {
        this.DR$STEP = DR$STEP;
    }

    public void setChanges(Delay value) {
        if (!Strings.isNullOrEmpty(value.DR$STEP) && !value.DR$STEP.equals(this.DR$STEP)) {
            this.DR$STEP = value.DR$STEP;
        }
        if (value.DRKY != null && !value.DRKY.equals(this.DRKY)) {
            this.DRKY = value.DRKY;
        }
        if (value.getDepartment() != null && !value.getDepartment().equals(this.getDepartment())) {
            this.department = value.getDepartment();
        }
        if (!Strings.isNullOrEmpty(value.description) && value.description.equals(this.description)) {
            this.description = value.description;
        }
        if (!Strings.isNullOrEmpty(value.DRLOCN) && value.DRLOCN.equals(this.DRLOCN)) {
            this.DRLOCN = value.DRLOCN;
        }
    }

    @Override
    public String toString() {
        return "Delay{"
                + "id=" + id
                + ",DRKY=" + DRKY
                + ",department=" + department
                + ",DRLOCN=" + DRLOCN
                + ",DR$STEP=" + DR$STEP
                + ",description=" + description + '}';
    }
} // class Delay
