package cmms.models;

import com.google.common.base.Strings;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

/**
 *
 * @author gpatitakis
 */
@Entity
@Table(name = "vlocations")
public class Department implements Serializable {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------
    // An autogenerated id (unique for each department in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "Q3KEY")
    private Long id;
    
    private Long Q3KEY_NEW;

    @NotNull
    private String Q3LOCN;

    @NotNull
    private String Q3DSC1;

    @NotNull
    private String Q3DSC3;

    @NotNull
    private String Q3DSC4;
    
    @NotNull
    @Column(name = "Q3DSC5")
    private String description;

    @NotNull
    private String Q3$STEP;

    @NotNull
    private String Q3DSC2;

    @NotNull
    private String Q3MCU;

    @NotNull
    @Column(name = "Q3$OFFSET_START")
    private Integer runningDuration;

    @NotNull
    @Column(name = "Q3$OFFSET_STOP")
    private Integer stoppingDuration;

    @Transient
    private String causes;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------
    public Department() {
    }

    public Department(Long id) {
        this.id = id;
    }

    // Getter and setter methods
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getQ3KEY_NEW() {
        return Q3KEY_NEW;
    }

    public void setQ3KEY_NEW(Long Q3KEY_NEW) {
        this.Q3KEY_NEW = Q3KEY_NEW;
    }

    public String getQ3LOCN() {
        return Q3LOCN;
    }

    public void setQ3LOCN(String Q3LOCN) {
        this.Q3LOCN = Q3LOCN;
    }

    public String getQ3DSC1() {
        return Q3DSC1;
    }

    public void setQ3DSC1(String Q3DSC1) {
        this.Q3DSC1 = Q3DSC1;
    }

    public String getQ3DSC3() {
        return Q3DSC3;
    }

    public void setQ3DSC3(String Q3DSC3) {
        this.Q3DSC3 = Q3DSC3;
    }

    public String getQ3DSC4() {
        return Q3DSC4;
    }

    public void setQ3DSC4(String Q3DSC4) {
        this.Q3DSC4 = Q3DSC4;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getQ3$STEP() {
        return Q3$STEP;
    }

    public void setQ3$STEP(String Q3$STEP) {
        this.Q3$STEP = Q3$STEP;
    }

    public String getQ3DSC2() {
        return Q3DSC2;
    }

    public void setQ3DSC2(String Q3DSC2) {
        this.Q3DSC2 = Q3DSC2;
    }

    public String getQ3MCU() {
        return Q3MCU;
    }

    public void setQ3MCU(String Q3MCU) {
        this.Q3MCU = Q3MCU;
    }

    public Integer getRunningDuration() {
        return runningDuration;
    }

    public void setRunningDuration(Integer runningDuration) {
        this.runningDuration = runningDuration;
    }

    public Integer getStoppingDuration() {
        return stoppingDuration;
    }

    public void setStoppingDuration(Integer stoppingDuration) {
        this.stoppingDuration = stoppingDuration;
    }

    public String getCauses() {
        return causes;
    }

    public void setCauses(String causes) {
        this.causes = causes;
    }

    public void setChanges(Department value) {
        if (value.runningDuration != null && !value.runningDuration.equals(this.runningDuration)) {
            this.runningDuration = value.runningDuration;
        }
        if (value.stoppingDuration != null && value.stoppingDuration.equals(this.stoppingDuration)) {
            this.stoppingDuration = value.stoppingDuration;
        }
        if (!Strings.isNullOrEmpty(value.description) && !value.description.equals(this.description)) {
            this.description = value.description;
        }
    }

    @Override
    public String toString() {
        return "Department{"
                + "id=" + id
                + ",runningDuration=" + runningDuration
                + ",stoppingDuration=" + stoppingDuration
                + ",description=" + description + '}';
    }
} // class Department
