/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cmms.models;

import com.google.common.base.Strings;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 *
 * @author gpatitakis
 */
@Entity
@Table(name = "subcause")
public class Subcause implements Serializable {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotNull
    @Column(columnDefinition = "0")
    private Long cause;

    @NotNull
    @Column(columnDefinition = "b'1'")
    private Boolean enable;

    private String code;

    private String description;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------
    public Subcause() {
    }

    public Subcause(Long id) {
        this.id = id;
    }

    public Subcause(Long cause, Boolean enable, String code, String description) {
        this.cause = cause;
        this.enable = enable;
        this.code = code;
        this.description = description;
    }

    // Getter and setter methods
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCause() {
        return cause;
    }

    public void setCause(Long cause) {
        this.cause = cause;
    }

    public Boolean isEnable() {
        return enable;
    }

    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setChanges(Subcause value) {
        if (!value.enable.equals(this.enable)) {
            this.enable = value.enable;
        }
        if (!Strings.isNullOrEmpty(value.code) && value.code.equals(this.code)) {
            this.code = value.code;
        }
        if (!Strings.isNullOrEmpty(value.description) && value.description.equals(this.description)) {
            this.description = value.description;
        }
    }

    @Override
    public String toString() {
        return "Subcause{"
                + "id=" + id
                + ",enable=" + enable
                + ",code=" + code
                + ",description=" + description + '}';
    }
} // class Subcause
