/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cmms.models;

import com.google.common.base.Strings;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 *
 * @author gpatitakis
 */
@Entity
@Table(name = "user_department")
public class UserDepartment implements Serializable {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotNull
    private String users;

    @NotNull
    private Long department;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------
    public UserDepartment() {
    }

    public UserDepartment(Long id) {
        this.id = id;
    }

    public UserDepartment(String users, Long department) {
        this.users = users;
        this.department = department;
    }

    // Getter and setter methods
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsers() {
        return users;
    }

    public void setUsers(String users) {
        this.users = users;
    }

    public Long getDepartment() {
        return department;
    }

    public void setDepartment(Long department) {
        this.department = department;
    }

    public void setChanges(UserDepartment value) {
        if (value.department != null && !value.department.equals(this.department)) {
            this.department = value.department;
        }
        if (!Strings.isNullOrEmpty(value.users) && !value.users.equals(this.users)) {
            this.users = value.users;
        }
    }

    @Override
    public String toString() {
        return "User{"
                + "id=" + id
                + ",department=" + department
                + ",users=" + users + '}';
    }
}
