/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cmms.models;

import com.google.common.base.Strings;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 *
 * @author gpatitakis
 */
@Entity
@Table(name = "user_type")
public class UserType implements Serializable {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotNull
    private String name;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------
    public UserType() {
    }

    public UserType(long id) {
        this.id = id;
    }

    // Getter and setter methods
    public long getId() {
        return id;
    }

    public void setId(long value) {
        this.id = value;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setChanges(UserType value) {
        if (!Strings.isNullOrEmpty(value.name) && value.name.equals(this.name)) {
            this.name = value.name;
        }
    }

    @Override
    public String toString() {
        return "CouseType{"
                + "id=" + id
                + ",name=" + name + '}';
    }
} // class UserType
